from typing import Protocol, runtime_checkable


@runtime_checkable
class InferenceBackend(Protocol):
    def chat(self, prompt: str) -> str: ...
    def ping(self) -> bool: ...
    def metrics(self) -> dict: ...
